num1=rbind(rep("A",3),rep("B",3),rep("C",3))
print("num1")
print(num1)
num2=rbind(rep("P",3),rep("Q",3),rep("R",3))
print("num2")
print(num2)
num3=rbind(rep("X",3),rep("Y",3),rep("Z",3))
print("num3")
print(num3)
a=matrix(t(cbind(num1,num2,num3)),ncol=3,byrow=T) 
print("Array Combined to Matrix : ")
print(a)