data(airquality)
summary(airquality)
library(reshape2)
melted_data <- melt(airquality)
head(melted_data)
melted_with_id <- melt(airquality, id.vars = c("Month", "Day"))
head(melted_with_id)
casted_data <- dcast(melted_with_id, Month + Day ~ variable)
head(casted_data)
data(airquality)
summary(airquality)
library(reshape2)
melted_data <- melt(airquality)
head(melted_data)
melted_with_id <- melt(airquality, id.vars = c("Month", "Day"))
head(melted_with_id)
casted_data <- dcast(melted_with_id, Month + Day ~ variable)
head(casted_data)
averages_per_month <- dcast(melted_with_id, Month ~ variable, mean)
averages_per_month
averages_per_month <- dcast(melted_with_id, Month ~ variable, mean)
averages_per_month